spring:
  output:
    ansi:
      enabled: always
  servlet:
    multipart:
      max-file-size: 20MB

external:
  jwt:
    secret: bangkum@#!
  map:
    api:
      key: 46b3b45f86bcab6cf712624343656024

  file:
    upload:
      path: /Users/lichee55/tmp/uploads

---

spring:
  config:
    activate:
      on-profile: local

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/test
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true

---

spring:
  config:
    activate:
      on-profile: prod
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://
    username: sa
    password: sa
  jpa:
    hibernate:
      ddl-auto: validate