spring:
  output:
    ansi:
      enabled: always
  servlet:
    multipart:
      enabled: true
      max-file-size: 20MB
      max-request-size: 20MB

  mail:
    host: mail.kumoh.ac.kr
    username: youngbin1000@kumoh.ac.kr
    password: gkdbflatkfkdgo!2
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          timeout: 5000

    default-encoding: utf-8
    port: 25


external:
  jwt:
    secret: teamse-bangkum--kit-7540-20171181
  map:
    api:
      key: 46b3b45f86bcab6cf712624343656024
  static:
    url:
      outbound: /image/**
      inbound: /Users/lichee55/tmp/uploads/


---

spring:
  config:
    activate:
      on-profile: local
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/test
    username: sa
    password:
external:
  static:
    url:
      outbound: /image/**
      inbound: /Users/lichee55/tmp/uploads/

---

spring:
  config:
    activate:
      on-profile: prod
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://172.17.0.3:3306/kumbangapi
    username: kumbangadmin
    password: se75407540
  jpa:
    hibernate:
      ddl-auto: validate
external:
  static:
    url:
      outbound: /image/**
      inbound: /uploads/